### ISSUE TITLE
[Feature request] Add a LCOV coverage reporter

### ISSUE THREAD

**Issue by cedx** [massiveinteractive/mcover#52]
Currently `MCoverage.getLogger().report()` prints a coverage report on the standard output.

What I want is to be able to collect coverage data and send it to the [Coveralls service](https://coveralls.io).
So I need a way to get the coverage data instead of printing on the command line, and ideally have that coverage data formatted to [LCOV](http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php) (as this format is very easy to parse : see the `FILES` section of the provided link).

Thanks in advance.

**Comment by elsassph** [comment]
Hello, mcover includes a LCOV reporter client:
https://github.com/massiveinteractive/mcover/blob/master/test/TestMain.hx#L33

**Comment by cedx** [comment]
Thanks a lot @elsassph! I have just one problem: I'm testing a Node.js program.
In the repository, the `LcovPrintClient` class uses the condition `if (sys || nodejs)`... but on Haxelib, the same file uses `if sys` only:
https://lib.haxe.org/p/mcover/2.2.1/files/mcover/coverage/client/LcovPrintClient.hx

Could you release a new version of the `mcover` package?

**Comment by elsassph** [comment]
Oh wow, this was changed 2 days after the 2.2.1 release indeed and wasn't released since.

**Comment by elsassph** [comment]
2.2.2 released now

**Comment by cedx** [comment]
It works! Merci beaucoup @elsassph.
I think I've found another problem, but I need to confirm it (i.e. coverage is incomplete). Will open a new issue.

**Comment by elsassph** [comment]
De rien :)
